#!/bin/bash


printf "%s\n" "                                           "
printf "%s\n" "                     .                     "
printf "%s\n" "                   ,&                      "
printf "%s\n" "                  ,&                       "
printf "%s\n" "                 ,&                        "
printf "%s\n" "                ,&                         "
printf "%s\n" "               ,&                          "
printf "%s\n" "              ,&                           "
printf "%s\n" "             ,&'                           "
printf "%s\n" "            ,&'                            "
printf "%s\n" "           ,&'                             "
printf "%s\n" "          ,&'                              "
printf "%s\n" "         ,&'                               "
printf "%s\n" "        ,&'                    ,           "
printf "%s\n" "        &'                      %          "
printf "%s\n" "       /(                        %         "
printf "%s\n" "       @(                        ||        "
printf "%s\n" "       \|       ,.eee.__        _g         "
printf "%s\n" "        '&,,____ ^*&&@@@@@nasey@^          "
printf "%s\n" "            ^^^^^*a,                       "
printf "%s\n" "                   ^1                      "
printf "%s\n" "                                           "
